golemfactory/golem-docs

docs/creators/javascript/docs/classes/executor_executor.TaskExecutor.md, docs/creators/javascript/examples/simple.md
I ran into an error in the docs where `providerCtx.ctx` was not defined so I changed it to ctx.run based on other examples.
=> fix: providerCtx not defined, should be ctx.run

src/markdoc/search.mjs
Search "Installing" in the search bar and select the second result. Notice that the page isn't automatically scrolled to the id of the URL 
this PR solves this
=> remove dashes from ids

src/components/ArticleType.jsx, src/components/Layout.jsx
=> Fix centering with tags next to ArticleType icon

src/markdoc/nodes.js, src/pages/docs/creators/dapps/creating-golem-dapps.md, src/pages/docs/creators/dapps/index.md, src/pages/docs/golem/payload-manifest/index.md, verify-headings.js
This PR fixes the articles that had markdown syntax inside the headings, which resulted in id's not being generated for the headings and caused articles to look funky. This has been addressed and now we also have a verify-headings.js script which can find some of these for us in the future.
=> Fix non-standard headings + mitigations for the future.

.github/workflows/build-reference-and-issue-pr.yml
Our current Github actions setup prematurely terminates the reference generation process across all branches if a single one encounters a failure. 
For instance, on the Alpha branch of `golem-js`, a required script for fixing the reference overview isn't merged yet. This causes the reference generation to fail on Alpha branch, prematurely terminating the process on other branches that, otherwise, would have succeeded.
I propose to modify the Github actions setup to allow the reference generation process to continue on other branches, even if one of them fails.
=> Dont use fail-fast on branch failure

src/pages/docs/creators/javascript/examples/switching-to-mainnet.md, src/pages/docs/creators/javascript/examples/tools/managing-golem-wallet.md, src/pages/docs/creators/javascript/guides/switching-to-mainnet.md, src/pages/docs/creators/javascript/guides/task-model.md, src/pages/docs/creators/javascript/quickstarts/quickstart.md, src/pages/docs/golem/overview/index.md, src/pages/docs/golem/payments/golem-token-conversion.md, src/pages/docs/golem/payments/layer-2-payments.md, src/pages/docs/providers/maintenance/provider-maintenance.md, src/pages/docs/quickstarts/js-quickstart.md
no yagna payment init is needed anymore,
goerli IS default in JS SDK,
=> removed info about default networks

src/components/Search.jsx, src/markdoc/search.mjs, src/pages/404.md, src/pages/500.md
Currently the search function indexes the custom error 404 and 500 pages, which is not intended. 
I have now made it so that pages with the type `noindex` doesn't get indexed in the search.
=> Mini fixes for demo

src/pages/_app.jsx, src/pages/docs/creators/javascript/examples/selecting-providers.md
The example now only checks for 5 providers instead of 10 due to a new change in the golem-js repo to fix the examples failure
=> Update docs according to example change

src/components/Layout.jsx
Since we introduced the component we've made changes and this means that the feedback is asked on home `/` homepage which we don't want. This PR fixes it.
=> Dont display feedback on homepage

src/markdoc/partials/ray/installation-alert.md, src/markdoc/partials/ray/quickstart.md, src/pages/docs/creators/ray/conversion-to-ray-on-golem-tutorial.md, src/pages/docs/creators/ray/setup-tutorial.md
1) I've added an informational alert to emphasize that "yagna" is tightly integrated with this package.
2) I've also decided to remove the alert about the virtual environment (venv). My reasoning is:
* Users who are familiar with setting up venvs and want to use them will naturally do so without needing a prompt.
* Those who don't usually set up venvs won't suddenly start just because of a brief alert. If we provided detailed instructions on how to do it, then there might have been a chance - but it might also overcomplicate the article.
=> Proposed Ray PR changes

generateTypedoc.mjs, src/pages/docs/golem-js/reference/default-values.md
Currently the default-values in the navbar links to a file that doesn't exist, thus it doesn't work. This PR solves that issue
=> Fix the reference default values page being missing

src/pages/docs/creators/index.md
@cryptobench 
When Python docs got merged the squares on the Create on Golem seem to direct Python to yapapi.
So with Jacek we thought we will change `Ray on Golem Docs` to `Python with Ray on Golem`
It seems too long however - can you have a look, how does it look? :pray:
=> Python with Ray

src/pages/docs/creators/ray/troubleshooting.md
In this PR:
- pointers to status & dashboard in troubleshooting
- reformulation of restarting troubleshooting section
- `head node not found` troubleshooting section
=> Ray troubleshooting after Previewer number 2

src/navigation/docs.js, src/navigation/footer.jsx, src/pages/docs/creators/ray/cluster-yaml.md, src/pages/docs/creators/ray/index.md, src/pages/docs/creators/ray/ray-on-golem-cli.md, src/pages/docs/creators/ray/troubleshooting.md
In this PR:
- `total_budget` yaml property described in `Cluster yaml` article
- `per_cpu_budget` yaml section described in `Cluster yaml` article
- `Ray on Golem CLI` article
=> Ray budget control options description

src/markdoc/partials/docs/accessing-the-internet.md, src/markdoc/partials/quickstarts/js-quickstart.md, src/pages/docs/creators/javascript/examples/accessing-internet.md, src/pages/docs/creators/javascript/tutorials/accessing-internet.md, src/pages/docs/creators/javascript/tutorials/quickstart-explained.md, src/pages/docs/creators/javascript/tutorials/running-in-browser.md, src/pages/docs/creators/javascript/tutorials/running-parallel-tasks.md
for quickstart - updated link to use the code from repo
replaced code in places where example is in the docs (not imported from golem-js repo) [that was outbound examples that is not in the repo yet + snippets in tutorials
=> get rid of deprecated methods in examples

src/navigation/docs.js
the article is under common, as is shared between js and python
=> update link to provider filesystem article

src/markdoc/partials/quickstarts/golem-in-a-browser.md, src/markdoc/partials/quickstarts/no-code-app-deployment.md
Now directly states the installation steps of yagna rather than navigating them away. This was based upon feedback that as a newcomer you would expect the quickstart guide to start from 0 and being to spin up something on golem.
Also did some grammar touches.
=> Quickstart feedback fixes

src/pages/docs/creators/golem-workers/hello-example.md, src/pages/docs/creators/golem-workers/sd-example.md
=> Golem-Workers: json files instead of in-line curls

src/components/SwaggerUI.jsx, src/markdoc/tags.js, src/navigation/docs.js, src/pages/docs/creators/golem-workers/api-swagger-ui.md, src/pages/docs/creators/golem-workers/basic-concepts.md, src/pages/docs/creators/golem-workers/create-node.md, src/pages/docs/creators/golem-workers/getting-started.md, src/pages/docs/creators/golem-workers/index.md, src/pages/docs/creators/golem-workers/troubleshooting.md
=> Golem-Workers Swagger UI

src/pages/docs/creators/golem-workers/getting-started.md
=> Golem-Workers: better link for cloning the repository
