docs/creators/javascript/index.md

the button leads to a 404 not found error right now

fix broken link

---

docs/creators/javascript/examples/hashcat.md
docs/creators/javascript/examples/hello.md
docs/creators/javascript/examples/simple.md
docs/creators/javascript/examples/web.md
docs/creators/javascript/high-level/architecture.md
docs/creators/javascript/high-level/index.md
docs/creators/javascript/high-level/task-model.md
docs/creators/javascript/index.md
docs/creators/javascript/mid-level/examples/hello.md
docs/creators/javascript/mid-level/examples/web.md
docs/creators/javascript/mid-level/index.md
docs/creators/javascript/quickstart.md
docs/css/custom-global.css
mkdocs.yml

mkdocs.yml and quickstart.md edits needs the most focus of these IMO

improving navigation and wording

---

docs/creators/dapps/creating-golem-dapps.md
docs/creators/dapps/troubleshooting.md
docs/creators/javascript/quickstart.md

Fix: typos

---

src/pages/docs/creators/javascript/tutorials/running-in-browser.md

I have reviewed the web tutorial and found some typos and phrases that could be improved, and I have corrected them in this PR. Please review and let me know if there's something you don't agree with.

JST-95: Text review/rephrasing

---

src/pages/docs/creators/dapps/troubleshooting.md
src/pages/docs/creators/javascript/examples/tools/restoring-golem-wallet.md
src/pages/docs/creators/javascript/examples/working-with-images.md
src/pages/docs/creators/javascript/examples/working-with-results.md
src/pages/docs/creators/javascript/tutorials/quickstart-explained.md
src/pages/docs/providers/maintenance/wallet-restoration.md

formating 

---

generate-reference.sh

This will add titles / descriptions to the reference pages instead of it saying **undefined**

Use new frontmatter plugin

---

src/pages/docs/creators/javascript/examples/composing-tasks.md
src/pages/docs/creators/javascript/examples/selecting-providers.md
src/pages/docs/creators/javascript/examples/switching-to-mainnet.md
src/pages/docs/creators/javascript/examples/transferring-data.md
src/pages/docs/creators/javascript/examples/using-app-keys.md
src/pages/docs/creators/javascript/examples/working-with-images.md
src/pages/docs/creators/javascript/examples/working-with-results.md
src/pages/docs/creators/javascript/guides/switching-to-mainnet.md
src/pages/docs/creators/javascript/guides/task-model.md

removed instances of double introduction and missing introductions

fix structure

---

src/markdoc/partials/retrievable-task-quickstart.md
src/pages/docs/creators/javascript/quickstarts/retrievable-task.md
src/pages/docs/quickstarts/retrievable-task.md

Right now on prod the title for these pages is `undefined`

fix: add title and description to pages using the retrievable task partial

---

.github/workflows/validate_links.yml
package-lock.json
package.json

Right now if an authors preview fails, then don't know why. Most likely its due to broken links and its impossible to see on the PR. I have created a workflow that will run on all PR's to check the links.

Use github actions to check links for authors not logged into vercel

---

src/markdoc/partials/quickstarts/js-quickstart.md
src/pages/docs/creators/javascript/examples/accessing-internet.md
src/pages/docs/creators/javascript/examples/composing-tasks.md
src/pages/docs/creators/javascript/examples/executing-tasks.md
src/pages/docs/creators/javascript/examples/selecting-providers.md
src/pages/docs/creators/javascript/examples/switching-to-mainnet.md
src/pages/docs/creators/javascript/examples/tools/converting-docker-image-to-golem-format.md
src/pages/docs/creators/javascript/examples/tools/yagna-installation-for-requestors.md
src/pages/docs/creators/javascript/examples/transferring-data.md
src/pages/docs/creators/javascript/examples/using-app-keys.md
src/pages/docs/creators/javascript/examples/working-with-images.md
src/pages/docs/creators/javascript/examples/working-with-results.md
src/pages/docs/creators/javascript/tutorials/running-parallel-tasks.md
src/pages/docs/creators/python/examples/tools/yagna-installation-for-requestors.md
src/pages/docs/templates/example-template.md
src/pages/docs/templates/tutorial-template.md

Updated minimum node version to 18

---

src/components/CustomError.jsx
src/components/Footer.jsx
src/components/Layout.jsx
src/components/Navigation.jsx
src/components/Search.jsx
src/pages/index.md

The new 404 changes can be seen by going to 
Normal 404:
/qwjoqwqi 
Custom message for handbook users:
/qwjoqwqi?fromhandbook

Upgraded 404, 500 and dark-mode fixes

---

src/pages/docs/providers/maintenance.md

remove the -k option in the provider update instructions (correct syntax was in faq and installation sections)

Update provider update instructions

---

.gitignore
src/navigation/docs.js
src/pages/docs/creators/javascript/guides/error-handling.md

doc: added error handling guide

---

src/pages/docs/degen/index.md

still need to:
work on the GLM fund procedure (criteria, limits, link, procedure details)
clean the example

Degenhack manual 

---

src/navigation/docs.js
src/pages/docs/golem/index.md
src/pages/docs/golem/terms.md

link to privacy policy updated, link to cookie policy added, index page updated, terms moved to the bottom of general menu

Policy update

---

src/components/Analytics/AnalyticsBanner.jsx
src/components/Analytics/AnalyticsEnabled.jsx
src/pages/_app.jsx

It probably needs some link to a privacy policy? Not sure what one to use @jalas167

Add cookie consent

---

src/markdoc/partials/quickstarts/retrievable-task-quickstart.md
src/pages/docs/creators/javascript/guides/retrievable-tasks.md
src/pages/docs/creators/javascript/tutorials/rest-api-with-express.md

Cherry picked changes that were already approved and merged to beta: https://github.com/golemfactory/golem-docs/pull/200

Update Job API documentation

---

src/markdoc/partials/ray/quickstart.md
src/pages/docs/creators/ray/index.md
src/pages/docs/creators/ray/setup-tutorial.md

ray reputation description et al

---

src/pages/docs/providers/provider-installation.md

We'll do the release after this gets merged

Update golemsp output to match 0.15.0 release

---

src/components/Feedback.jsx

Fix feedback form

---

src/markdoc/partials/ray/quickstart.md
src/pages/docs/creators/ray/cluster-yaml.md
src/pages/docs/creators/ray/conversion-to-ray-on-golem-tutorial.md
src/pages/docs/creators/ray/index.md
src/pages/docs/creators/ray/mainnet.md
src/pages/docs/creators/ray/ray-on-golem-cli.md
src/pages/docs/creators/ray/setup-tutorial.md
src/pages/docs/creators/ray/supported-versions-and-other-limitations.md

Ray MVP docs (including new features)

---

src/pages/docs/creators/javascript/guides/switching-to-mainnet.md
src/pages/docs/creators/python/examples/tools/managing-golem-wallet.md
src/pages/docs/creators/python/guides/switching-to-mainnet.md

Proposed changes in doc to include references to Onboarding Portal

Onboarding Portal

---

src/navigation/docs.js
src/navigation/footer.jsx
src/pages/docs/creators/ray/basic-ray-tasks-usage-tutorial.md
src/pages/docs/creators/ray/cluster-yaml.md
src/pages/docs/creators/ray/index.md
src/pages/docs/creators/ray/supported-versions-and-other-limitations.md

Hide links to a broken ray example

hide conversion article links

---

src/markdoc/partials/golem-workers/verify-fund.md
src/pages/docs/creators/golem-workers/basic-concepts.md
src/pages/docs/creators/golem-workers/create-node.md
src/pages/docs/creators/golem-workers/getting-started.md
src/pages/docs/creators/golem-workers/hello-example.md
src/pages/docs/creators/golem-workers/index.md
src/pages/docs/creators/golem-workers/sd-example.md
src/pages/docs/creators/golem-workers/troubleshooting.md

Golem-Workers beta tests fixes #1
